[package]
name = "monitor-media"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
crossbeam-channel.workspace = true
fs2.workspace = true
monitor-storage = { path = "../monitor-storage" }
serde.workspace = true
tracing.workspace = true
windows.workspace = true

[dev-dependencies]
tempfile.workspace = true
